### ISSUE TITLE
Order of PDF pages displayed

### ISSUE THREAD

**Issue by HighPoint** [aws-samples/amazon-comprehend-semi-structured-documents-annotation-tools#15]
Is there a way to set the order of the PDF pages shown? Currently, for a lengthy PDF, the pages seem randomly selected. For instance, in a 22-page PDF, page 9 was shown first then page 7. Can this be changed to display page 1 first, page 2 second, etc? For our use case, the most important page is page 1. Thank you for your help!

**Comment by dnlen** [comment]
There is no current method to order the pages sequentially as we utilize the Sagemaker GroundTruth labeling job process which loads the job tasks asynchronously. This sequential labeling task has been discussed and is in our backlog, but there is no set date for when the feature will be released.

As a possible workaround, you can possibly split your PDF pages and create separate labeling jobs for them and include the PDF name and page number in the `--job-prefix-name` option in order to see the PDF pages clearly in the labeling portal.
```
AWS_REGION=`aws configure get region`;
AWS_ACCOUNT_ID=`aws sts get-caller-identity | jq -r '.Account'`;
python bin/comprehend-ssie-annotation-tool-cli.py \
    --input-s3-path s3://comprehend-semi-structured-docs-${AWS_REGION}-${AWS_ACCOUNT_ID}/docs/ \
    --cfn-name sam-app \
    --work-team-name <work-team-name> \
    --region ${AWS_REGION} \
    --job-name-prefix "PDF1-1" \
    --entity-types "EntityTypeA, EnityTypeB, EntityTypeC";

AWS_REGION=`aws configure get region`;
AWS_ACCOUNT_ID=`aws sts get-caller-identity | jq -r '.Account'`;
python bin/comprehend-ssie-annotation-tool-cli.py \
    --input-s3-path s3://comprehend-semi-structured-docs-${AWS_REGION}-${AWS_ACCOUNT_ID}/docs/ \
    --cfn-name sam-app \
    --work-team-name <work-team-name> \
    --region ${AWS_REGION} \
    --job-name-prefix "PDF1-2" \
    --entity-types "EntityTypeA, EnityTypeB, EntityTypeC";

...
```
