### ISSUE TITLE
Is my dataset randomly split every time I train a new NER model?

### ISSUE THREAD

**Issue by jetsonai11** [aws-samples/amazon-comprehend-semi-structured-documents-annotation-tools#16]
Hi @dnlen, the dataset has been split automatically, but it seems like the same set of data has been allocated to the training/validation/test set, because after I trained a new model, I am getting the same model performance. How can I use different data for training and perform cross-validations? I was exploring to split the data using SageMaker Data Wrangler, but would it be able to work on the annotation files and the manifest file obtained from this Comprehend annotation tool?

<img width="144" alt="Screen Shot 2022-07-18 at 6 02 50 PM" src="https://user-images.githubusercontent.com/64779050/179624985-064489ea-e904-42a5-b5e6-958f73f79eed.png">

**Comment by dnlen** [comment]
For more information on your trained Comprehend model, you can go to your model in the console and go to the Application Integration tab where you can see details such as the NumberOfTrainMentions for each entity. Could you check to see if the numbers are the same for each entity for both trained models? This is to validate the perceived non-random splitting of data during training.

The annotation files and manifest file from the Comprehend annotation tool were not planned to be integrated for usage with Sagemaker Data Wrangler. It may be doable but some data manipulation may be required.

**Comment by jetsonai11** [comment]
Hi @dnlen  - no the number are not the same.
<img width="197" alt="Screen Shot 2022-07-20 at 4 17 56 PM" src="https://user-images.githubusercontent.com/64779050/180073836-4618169c-b121-4b56-a648-22a183ab64fb.png">

**Comment by dnlen** [comment]
Because of the different numbers for "Number of train mentions", this validates that the data allocated to train/test/validation is not the same in every training job.

We do not allow the option to split data into 3 (train/test/validation) yourself, but you can split the data into 2 to use for training/validation and test using our Split attribute https://docs.aws.amazon.com/comprehend/latest/dg/API_AugmentedManifestsListItem.html#comprehend-Type-AugmentedManifestsListItem-Split
