### ISSUE TITLE
GUI not loading

### ISSUE THREAD

**Issue by ujnm** [aws-samples/amazon-comprehend-semi-structured-documents-annotation-tools#2]
After following the steps and creating labeling job, when opening it as annotator no gui is loading, there is only blank page.

**Comment by dnlen** [comment]
Hi ujnm, there is no gui loading in this case because of an issue with the ui-template folder in the package not being uploading correctly to S3 when the script is run to create a labeling job. This issue should be resolved with the solution from this other issue:
https://github.com/aws-samples/amazon-comprehend-semi-structured-documents-annotation-tools/issues/1#issuecomment-959611830

**Comment by ujnm** [comment]
Solution works, thank you :)
